apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-service
  namespace: zestify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-service
  template:
    metadata:
      labels:
        app: realtime-service
    spec:
      containers:
        - name: realtime
          image: surya850/zestify-realtime:1a3de767142fe376e5783383e2a7137fe7a2a7cc
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: zestify-config
                  key: NODE_ENV
            - name: JWT_SEC
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: JWT_SEC
            - name: INTERNAL_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: INTERNAL_SERVICE_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: REDIS_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 5
