apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: zestify:apps/Deployment:zestify/auth-service
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"zestify:apps/Deployment:zestify/auth-service"},"name":"auth-service","namespace":"zestify"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"auth-service"}},"template":{"metadata":{"labels":{"app":"auth-service"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"5000"},{"name":"NODE_ENV","valueFrom":{"configMapKeyRef":{"key":"NODE_ENV","name":"zestify-config"}}},{"name":"JWT_SEC","valueFrom":{"secretKeyRef":{"key":"JWT_SEC","name":"zestify-secrets"}}},{"name":"INTERNAL_SERVICE_KEY","valueFrom":{"secretKeyRef":{"key":"INTERNAL_SERVICE_KEY","name":"zestify-secrets"}}},{"name":"MONGO_URI","valueFrom":{"secretKeyRef":{"key":"MONGO_URI","name":"zestify-secrets"}}},{"name":"GOOGLE_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"GOOGLE_CLIENT_ID","name":"zestify-secrets"}}},{"name":"GOOGLE_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"GOOGLE_CLIENT_SECRET","name":"zestify-secrets"}}},{"name":"REDIS_URL","valueFrom":{"secretKeyRef":{"key":"REDIS_URL","name":"zestify-secrets"}}}],"image":"surya850/zestify-auth:20e2e98f682b06c0fe1b1b344538faa6be6d41e4","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":5000},"initialDelaySeconds":30,"periodSeconds":10},"name":"auth","ports":[{"containerPort":5000}],"readinessProbe":{"httpGet":{"path":"/health","port":5000},"initialDelaySeconds":10,"periodSeconds":5},"resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2026-05-29T16:52:24Z"
  generation: 6
  name: auth-service
  namespace: zestify
  resourceVersion: "1780080492731983013"
  uid: cded8ae2-58b7-4a59-aa4d-4cabd9cd3edd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-05-29T17:10:08Z"
      labels:
        app: auth-service
    spec:
      containers:
      - env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: zestify-config
        - name: JWT_SEC
          valueFrom:
            secretKeyRef:
              key: JWT_SEC
              name: zestify-secrets
        - name: INTERNAL_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              key: INTERNAL_SERVICE_KEY
              name: zestify-secrets
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: MONGO_URI
              name: zestify-secrets
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GOOGLE_CLIENT_ID
              name: zestify-secrets
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: GOOGLE_CLIENT_SECRET
              name: zestify-secrets
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: REDIS_URL
              name: zestify-secrets
        image: surya850/zestify-auth:20e2e98f682b06c0fe1b1b344538faa6be6d41e4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: auth
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-05-29T17:09:42Z"
    lastUpdateTime: "2026-05-29T17:09:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-05-29T17:03:10Z"
    lastUpdateTime: "2026-05-29T18:48:11Z"
    message: ReplicaSet "auth-service-849ccbdb79" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  terminatingReplicas: 0
  updatedReplicas: 1
