apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
  namespace: zestify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
        - name: rider
          image: surya850/zestify-rider:235c24a7a206dc9d21388ef6a2419b3daece0df4
          ports:
            - containerPort: 5005
          env:
            - name: PORT
              value: "5005"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: zestify-config
                  key: NODE_ENV
            - name: JWT_SEC
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: JWT_SEC
            - name: INTERNAL_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: INTERNAL_SERVICE_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: MONGO_URI
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: zestify-secrets
                  key: RABBITMQ_URL
            - name: REALTIME_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: zestify-config
                  key: REALTIME_SERVICE
            - name: RESTAURANT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: zestify-config
                  key: RESTAURANT_SERVICE
            - name: UTILS_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: zestify-config
                  key: UTILS_SERVICE
            - name: RIDER_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: zestify-config
                  key: RIDER_QUEUE
            - name: ORDER_READY_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: zestify-config
                  key: ORDER_READY_QUEUE
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 10
            periodSeconds: 5
